## Use an official OpenJDK image from the Docker Hub
#FROM openjdk:17-jdk-alpine
#
## Set the application's JAR file name
#ARG JAR_FILE=target/app.jar
#
## Copy the application's JAR file into the Docker image
#COPY ${JAR_FILE} app.jar
#
## Expose the port your Spring Boot app runs on
#EXPOSE 9000
#
## Run the JAR file when the container starts
#ENTRYPOINT ["java", "-jar", "/app.jar"]
